param(
    [string]$NamdExe = "C:\Users\student\mat306\NAMD_3.0.2_Win64-multicore-CUDA\namd3.exe",
    [int]$Cores = 8,
    [ValidateSet("all", "1e6", "1e8")]
    [string]$RunSet = "all",
    [switch]$Resume,
    [string]$SummaryCsv = "namd_sweep_summary.csv",
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$ProgressPreference = "Continue"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

$SessionLog = Join-Path $ScriptDir "run_namd_sweep_console.log"

function Write-Log {
    param(
        [string]$Message,
        [ValidateSet("INFO", "WARN", "ERROR")]
        [string]$Level = "INFO"
    )

    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[{0}] [{1}] {2}" -f $timestamp, $Level, $Message
    Write-Host $line
    Add-Content -Path $SessionLog -Value $line
}

if (Test-Path $SessionLog) {
    Remove-Item $SessionLog -Force
}

function Convert-ToNamdPath {
    param([string]$PathText)
    return $PathText -replace "\\", "/"
}

function Get-LastCompletedStep {
    param([string]$LogPath)

    if (-not (Test-Path $LogPath)) {
        return $null
    }

    $lastEnergy = Select-String -Path $LogPath -Pattern "^ENERGY:" | Select-Object -Last 1
    if ($null -eq $lastEnergy) {
        return $null
    }

    $tokens = ($lastEnergy.Line -split "\s+") | Where-Object { $_ -ne "" }
    if ($tokens.Count -lt 2) {
        return $null
    }

    try {
        return [int64]$tokens[1]
    }
    catch {
        return $null
    }
}

function New-NamdConfig {
    param(
        [hashtable]$Job,
        [string]$Dir,
        [switch]$ResumeMode
    )

    $temp = $Job.TemperatureK
    $steps = [int64]$Job.Steps
    $stepLabel = $Job.StepLabel

    $baseName = "butane_{0}K_{1}" -f $temp, $stepLabel
    $outputPrefix = Join-Path $Dir $baseName
    $configPath = Join-Path $Dir ("{0}.namd" -f $baseName)
    $restartCoor = "$outputPrefix.restart.coor"
    $restartVel = "$outputPrefix.restart.vel"
    $restartXsc = "$outputPrefix.restart.xsc"
    $logPath = "$outputPrefix.log"

    $pdb = Convert-ToNamdPath (Join-Path $Dir "butane.pdb")
    $psf = Convert-ToNamdPath (Join-Path $Dir "butane.psf")
    $prm = Convert-ToNamdPath (Join-Path $Dir "par_all35_ethers-2.prm")
    $colvars = Convert-ToNamdPath (Join-Path $Dir "butane_dihedral.colvars")
    $outputPrefixNamd = Convert-ToNamdPath $outputPrefix
    $restartCoorNamd = Convert-ToNamdPath $restartCoor
    $restartVelNamd = Convert-ToNamdPath $restartVel
    $restartXscNamd = Convert-ToNamdPath $restartXsc
    $dcdFreq = 100000000

    $hasRestartCoor = Test-Path $restartCoor
    $hasRestartVel = Test-Path $restartVel
    $hasRestartXsc = Test-Path $restartXsc
    $useRestart = $ResumeMode -and $hasRestartCoor -and $hasRestartVel

    $firstTimestep = 0
    if ($useRestart) {
        $resumeStep = Get-LastCompletedStep -LogPath $logPath
        if ($null -ne $resumeStep) {
            $firstTimestep = $resumeStep
        }
    }

    $runSteps = $steps
    if ($useRestart) {
        if ($firstTimestep -ge $steps) {
            $runSteps = 0
        }
        else {
            $runSteps = $steps - $firstTimestep
        }
    }

    $restartNote = "no"
    $inputCoordinatesLine = "coordinates             ${pdb}"
    $inputVelLine = ""
    $inputXscLine = ""
    $prepLine1 = "minimize                1000"
    $prepLine2 = "reinitvels              `$temperature"

    if ($useRestart) {
        $restartNote = "yes"
        $inputCoordinatesLine = "binCoordinates          ${restartCoorNamd}"
        $inputVelLine = "binVelocities           ${restartVelNamd}"
        if ($hasRestartXsc) {
            $inputXscLine = "extendedSystem          ${restartXscNamd}"
        }
        $prepLine1 = "# continuing from restart files"
        $prepLine2 = "# keeping restart velocities"
    }

    $content = @"
# Auto-generated by run_namd_sweep_windows.ps1
# Run: ${temp} K, ${steps} MD steps
# Resume from restart: ${restartNote}

# input
${inputCoordinatesLine}
${inputVelLine}
${inputXscLine}
structure               ${psf}
parameters              ${prm}
paraTypeCharmm          on

# output
set output              ${outputPrefixNamd}
outputName              `$output
DCDfile                 `${output}.dcd
DCDfreq                 ${dcdFreq}

binaryoutput            yes
binaryrestart           yes
outputEnergies          10000
restartfreq             50000

fixedAtoms              off

# Basic dynamics
exclude                 scaled1-4
1-4scaling              1.0
COMmotion               no
dielectric              1.0

# Simulation space partitioning
switching               on
switchdist              9
cutoff                  10
pairlistdist            12

# Multiple timestepping
firsttimestep           ${firstTimestep}
timestep                1.0
stepspercycle           20
nonbondedFreq           2
fullElectFrequency      4

# Temperature control (K)
set temperature         ${temp}
temperature             `$temperature
langevin                on
langevinTemp            `$temperature
langevinDamping         5
langevinHydrogen        off

# Colvars (write dihedral instead of full trajectory)
colvars                 on
colvarsConfig           ${colvars}

# Scripting
${prepLine1}
${prepLine2}
run                     ${runSteps}
"@

    Set-Content -Path $configPath -Value $content -Encoding ascii
    Write-Log ("Generated config: {0} (Temp={1}K, TargetSteps={2}, Resume={3}, FirstTimestep={4}, RunSteps={5})" -f $configPath, $temp, $steps, $useRestart, $firstTimestep, $runSteps)

    return [PSCustomObject]@{
        TemperatureK = $temp
        Steps = $steps
        StepLabel = $stepLabel
        ConfigPath = $configPath
        OutputPrefix = $outputPrefix
        LogPath = $logPath
        RestartUsed = $useRestart
        FirstTimestep = $firstTimestep
        RunSteps = $runSteps
    }
}

function Start-NamdJob {
    param(
        [PSCustomObject]$Job,
        [string]$ExePath,
        [int]$CoreCount,
        [switch]$PreviewOnly
    )

    $configName = Split-Path -Leaf $Job.ConfigPath
    $logName = Split-Path -Leaf $Job.LogPath
    $args = @("+p$CoreCount", $configName)

    if ($PreviewOnly) {
        Write-Log ("DRY RUN: {0} {1} > {2}" -f $ExePath, ($args -join " "), $logName)
        return $null
    }

    Write-Log ("Starting job: Temp={0}K StepLabel={1} RunSteps={2}" -f $Job.TemperatureK, $Job.StepLabel, $Job.RunSteps)
    Write-Log ("Command: {0} {1}" -f $ExePath, ($args -join " "))
    Write-Log ("Stdout: {0}" -f $Job.LogPath)
    Write-Log ("Stderr: {0}" -f ($Job.LogPath + ".err"))

    return Start-Process -FilePath $ExePath -ArgumentList $args -WorkingDirectory (Split-Path -Parent $Job.ConfigPath) -RedirectStandardOutput $Job.LogPath -RedirectStandardError ($Job.LogPath + ".err") -PassThru
}

function Read-FinalEnergyStep {
    param([string]$LogPath)

    if (-not (Test-Path $LogPath)) {
        return "missing-log"
    }

    $lastEnergy = Select-String -Path $LogPath -Pattern "^ENERGY:" | Select-Object -Last 1
    if ($null -eq $lastEnergy) {
        return "no-energy-lines"
    }

    $tokens = ($lastEnergy.Line -split "\s+") | Where-Object { $_ -ne "" }
    if ($tokens.Count -lt 2) {
        return "parse-failed"
    }

    return $tokens[1]
}

Write-Log "Preparing NAMD sweep..."
Write-Log ("RunSet={0}; Resume={1}; DryRun={2}" -f $RunSet, [bool]$Resume, [bool]$DryRun)

if (-not (Test-Path $NamdExe)) {
    throw "NAMD executable not found: $NamdExe"
}

$required = @("butane.pdb", "butane.psf", "par_all35_ethers-2.prm", "butane_dihedral.colvars")
foreach ($f in $required) {
    $full = Join-Path $ScriptDir $f
    if (-not (Test-Path $full)) {
        throw "Required input file missing: $full"
    }
    Write-Log ("Found input file: {0}" -f $full)
}

$jobsSpec = @(
    @{ TemperatureK = 400;  Steps = 1000000;   StepLabel = "1e6" },
    @{ TemperatureK = 800;  Steps = 1000000;   StepLabel = "1e6" },
    @{ TemperatureK = 1200; Steps = 1000000;   StepLabel = "1e6" },
    @{ TemperatureK = 400;  Steps = 100000000; StepLabel = "1e8" },
    @{ TemperatureK = 800;  Steps = 100000000; StepLabel = "1e8" },
    @{ TemperatureK = 1200; Steps = 100000000; StepLabel = "1e8" }
)

$jobs = foreach ($spec in $jobsSpec) {
    New-NamdConfig -Job $spec -Dir $ScriptDir -ResumeMode:$Resume
}

$selectedJobs = @()
if ($RunSet -eq "all") {
    $selectedJobs = $jobs | Sort-Object Steps, TemperatureK
}
else {
    $selectedJobs = $jobs | Where-Object { $_.StepLabel -eq $RunSet } | Sort-Object TemperatureK
}

Write-Log ("Selected jobs: {0}" -f (($selectedJobs | ForEach-Object { "{0}K-{1}" -f $_.TemperatureK, $_.StepLabel }) -join ", "))

$allResults = @()

if ($selectedJobs.Count -gt 0) {
    Write-Log "Running all selected jobs sequentially"
    foreach ($job in $selectedJobs) {
        if ($job.RunSteps -le 0) {
            Write-Log ("Skipping job: Temp={0}K StepLabel={1} because FirstTimestep={2} already meets target" -f $job.TemperatureK, $job.StepLabel, $job.FirstTimestep) "WARN"
            $allResults += [PSCustomObject]@{
                TempK = $job.TemperatureK
                StepLabel = $job.StepLabel
                ExitCode = "skipped"
                FinalEnergyStep = $job.FirstTimestep
                EndOfProgram = "n/a"
                RestartUsed = $job.RestartUsed
                RunSteps = $job.RunSteps
                LogFile = $job.LogPath
            }
            continue
        }

        $p = Start-NamdJob -Job $job -ExePath $NamdExe -CoreCount $Cores -PreviewOnly:$DryRun
        if ($null -eq $p) {
            continue
        }

        if ($null -ne $p) {
            Write-Log ("Process started with PID {0}" -f $p.Id)
        }

        $progressId = 1
        while (-not $p.HasExited) {
            $currentEnergyStep = Read-FinalEnergyStep -LogPath $job.LogPath
            $status = "Running"
            if (Test-Path $job.LogPath) {
                $status = "Log active"
            }

            Write-Progress -Id $progressId -Activity ("NAMD {0}K {1}" -f $job.TemperatureK, $job.StepLabel) -Status ("Latest ENERGY step: {0}" -f $currentEnergyStep) -PercentComplete -1
            Start-Sleep -Seconds 5
            $p.Refresh()
        }
        Write-Progress -Id $progressId -Activity ("NAMD {0}K {1}" -f $job.TemperatureK, $job.StepLabel) -Completed

        $p.WaitForExit()
        Write-Log ("Process exited with code {0}" -f $p.ExitCode)

        $energyStep = Read-FinalEnergyStep -LogPath $job.LogPath
        Write-Log ("Last ENERGY step parsed from log: {0}" -f $energyStep)
        $normalEnd = "no"

        if (Select-String -Path $job.LogPath -Pattern "End of program" -Quiet) {
            $normalEnd = "yes"
        }
        else {
            Write-Log ("Job log does not contain 'End of program': {0}" -f $job.LogPath) "WARN"
        }

        $allResults += [PSCustomObject]@{
            TempK = $job.TemperatureK
            StepLabel = $job.StepLabel
            ExitCode = $p.ExitCode
            FinalEnergyStep = $energyStep
            EndOfProgram = $normalEnd
            RestartUsed = $job.RestartUsed
            RunSteps = $job.RunSteps
            LogFile = $job.LogPath
        }

        Write-Log ("Finished job: Temp={0}K StepLabel={1} ExitCode={2} FinalEnergyStep={3} EndOfProgram={4}" -f $job.TemperatureK, $job.StepLabel, $p.ExitCode, $energyStep, $normalEnd)
    }
}

if ($DryRun) {
    Write-Log "Dry run complete. No simulations launched."
    return
}

if ($allResults.Count -gt 0) {
    $summaryPath = Join-Path $ScriptDir $SummaryCsv
    $allResults | Sort-Object StepLabel, TempK | Export-Csv -Path $summaryPath -NoTypeInformation -Encoding ascii
    Write-Log ("CSV summary written: {0}" -f $summaryPath)

    Write-Log "Summary (all processed jobs):"
    $allResults | Sort-Object StepLabel, TempK | Format-Table -AutoSize
}

Write-Log "All requested jobs have been processed."
Write-Log ("Session log written to: {0}" -f $SessionLog)
